export const COUNTRIES = [
    { value: 'england', label: 'Inglaterra' },
    { value: 'spain', label: 'España' },
    { value: 'france', label: 'Francia' },
    { value: 'italy', label: 'Italia' },
    { value: 'usa', label: 'Estados Unidos' },
    { value: 'china', label: 'China' },
    { value: 'india', label: 'India' },
    { value: 'germany', label: 'Alemania' },
    { value: 'japan', label: 'Japón' },
    { value: 'canada', label: 'Canadá' },
    { value: 'australia', label: 'Australia' },
    { value: 'brazil', label: 'Brasil' },
    { value: 'russia', label: 'Rusia' },
    { value: 'mexico', label: 'México' },
    { value: 'south_korea', label: 'Corea del Sur' },
    { value: 'indonesia', label: 'Indonesia' },
    { value: 'turkey', label: 'Turquía' },
    { value: 'netherlands', label: 'Países Bajos' },
    { value: 'saudi_arabia', label: 'Arabia Saudita' },
    { value: 'switzerland', label: 'Suiza' },
    { value: 'argentina', label: 'Argentina' },
    { value: 'south_africa', label: 'Sudáfrica' },
    { value: 'egypt', label: 'Egipto' },
    { value: 'nigeria', label: 'Nigeria' },
    { value: 'pakistan', label: 'Pakistán' },
    { value: 'bangladesh', label: 'Bangladesh' },
    { value: 'iran', label: 'Irán' },
    { value: 'vietnam', label: 'Vietnam' },
    { value: 'philippines', label: 'Filipinas' },
    { value: 'colombia', label: 'Colombia' }
];

export const LANGUAGES = [
    { value: 'english', label: 'Inglés' },
    { value: 'spanish', label: 'Español' },
    { value: 'french', label: 'Francés' },
    { value: 'italian', label: 'Italiano' },
    { value: 'chinese', label: 'Chino' },
    { value: 'arabic', label: 'Árabe' },
    { value: 'hindi', label: 'Hindi' },
    { value: 'bengali', label: 'Bengalí' },
    { value: 'portuguese', label: 'Portugués' },
    { value: 'russian', label: 'Ruso' },
    { value: 'japanese', label: 'Japonés' },
    { value: 'german', label: 'Alemán' },
    { value: 'korean', label: 'Coreano' },
    { value: 'farsi', label: 'Persa' },
    { value: 'turkish', label: 'Turco' },
    { value: 'urdu', label: 'Urdu' },
    { value: 'swahili', label: 'Suajili' },
    { value: 'dutch', label: 'Holandés' },
    { value: 'polish', label: 'Polaco' },
    { value: 'vietnamese', label: 'Vietnamita' },
    { value: 'thai', label: 'Tailandés' },
    { value: 'greek', label: 'Griego' },
    { value: 'czech', label: 'Checo' },
    { value: 'swedish', label: 'Sueco' },
    { value: 'finnish', label: 'Finlandés' },
    { value: 'danish', label: 'Danés' },
    { value: 'norwegian', label: 'Noruego' },
    { value: 'hungarian', label: 'Húngaro' },
    { value: 'tagalog', label: 'Tagalo' },
    { value: 'malay', label: 'Malayo' },
];

